#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# ── Colors ──
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

echo -e "${BOLD}Setting up self-hosted Supabase for The Family${NC}"
echo ""

# ── Check dependencies ──
if ! command -v openssl &>/dev/null; then
  echo -e "${RED}Error: openssl is required but not installed.${NC}"
  exit 1
fi

# ── Require .env exists ──
if [ ! -f "$PROJECT_DIR/.env" ]; then
  echo -e "${RED}Error: No .env file found. Create one first:${NC}"
  echo "  cp .env.example .env"
  exit 1
fi

# ── Check if already set up ──
REGENERATING=false
if grep -q '^JWT_SECRET=' "$PROJECT_DIR/.env"; then
  echo -e "${YELLOW}Warning: Supabase vars already exist in .env.${NC}"
  read -rp "Regenerate? (y/N) " confirm
  if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 0
  fi
  REGENERATING=true
fi

# ── Generate secrets ──
echo -e "${CYAN}Generating secrets...${NC}"

POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -d '/+=')
JWT_SECRET=$(openssl rand -base64 48 | tr -d '/+=')
DASHBOARD_PASSWORD=$(openssl rand -base64 16 | tr -d '/+=')
SECRET_KEY_BASE=$(openssl rand -hex 64)
VAULT_ENC_KEY=$(openssl rand -base64 24 | tr -d '/+=')

# ── Generate JWT tokens (ANON_KEY and SERVICE_ROLE_KEY) ──
# These are JWTs signed with the JWT_SECRET, matching Supabase's expected format

generate_jwt() {
  local role="$1"
  local secret="$2"

  local header='{"alg":"HS256","typ":"JWT"}'
  local now
  now=$(date +%s)
  # Expire in 10 years
  local exp=$((now + 315360000))
  local payload="{\"role\":\"$role\",\"iss\":\"supabase\",\"iat\":$now,\"exp\":$exp}"

  local header_b64
  header_b64=$(printf '%s' "$header" | openssl base64 -A | tr '+/' '-_' | tr -d '=')
  local payload_b64
  payload_b64=$(printf '%s' "$payload" | openssl base64 -A | tr '+/' '-_' | tr -d '=')

  local signature
  signature=$(printf '%s.%s' "$header_b64" "$payload_b64" | openssl dgst -sha256 -hmac "$secret" -binary | openssl base64 -A | tr '+/' '-_' | tr -d '=')

  printf '%s.%s.%s' "$header_b64" "$payload_b64" "$signature"
}

ANON_KEY=$(generate_jwt "anon" "$JWT_SECRET")
SERVICE_ROLE_KEY=$(generate_jwt "service_role" "$JWT_SECRET")

# ── Write Supabase vars into .env ──
# Remove any existing Supabase vars to avoid duplicates
for var in POSTGRES_PASSWORD JWT_SECRET ANON_KEY SERVICE_ROLE_KEY \
           DASHBOARD_USERNAME DASHBOARD_PASSWORD SECRET_KEY_BASE \
           VAULT_ENC_KEY SMTP_ADMIN_EMAIL ENABLE_EMAIL_AUTOCONFIRM; do
  sed -i.bak "/^${var}=/d" "$PROJECT_DIR/.env"
done
# Also clean up any previous section header
sed -i.bak '/^# Self-Hosted Supabase/d' "$PROJECT_DIR/.env"
rm -f "$PROJECT_DIR/.env.bak"

# Append Supabase vars
cat >> "$PROJECT_DIR/.env" <<ENVEOF

# Self-Hosted Supabase (generated by setup-supabase.sh)
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
JWT_SECRET=$JWT_SECRET
ANON_KEY=$ANON_KEY
SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY
DASHBOARD_USERNAME=admin
DASHBOARD_PASSWORD=$DASHBOARD_PASSWORD
SECRET_KEY_BASE=$SECRET_KEY_BASE
VAULT_ENC_KEY=$VAULT_ENC_KEY
SMTP_ADMIN_EMAIL=admin@thefamily.local
ENABLE_EMAIL_AUTOCONFIRM=true
ENVEOF
echo -e "${GREEN}Added Supabase variables to .env${NC}"

# ── Enable the supabase profile ──
if grep -q '^COMPOSE_PROFILES=' "$PROJECT_DIR/.env"; then
  current=$(grep '^COMPOSE_PROFILES=' "$PROJECT_DIR/.env" | head -1 | cut -d= -f2-)
  if [[ "$current" == *"supabase"* ]]; then
    echo -e "${YELLOW}COMPOSE_PROFILES already includes 'supabase'${NC}"
  else
    sed -i.bak "s/^COMPOSE_PROFILES=\(.*\)/COMPOSE_PROFILES=\1,supabase/" "$PROJECT_DIR/.env"
    rm -f "$PROJECT_DIR/.env.bak"
    echo -e "${GREEN}Added 'supabase' to COMPOSE_PROFILES in .env${NC}"
  fi
else
  echo "COMPOSE_PROFILES=supabase" >> "$PROJECT_DIR/.env"
  echo -e "${GREEN}Added COMPOSE_PROFILES=supabase to .env${NC}"
fi

# ── Set frontend Supabase vars ──
# Replace existing VITE_SUPABASE_URL and VITE_SUPABASE_KEY with self-hosted values
sed -i.bak "s|^VITE_SUPABASE_URL=.*|VITE_SUPABASE_URL=http://localhost:8000|" "$PROJECT_DIR/.env"
sed -i.bak "s|^VITE_SUPABASE_KEY=.*|VITE_SUPABASE_KEY=$ANON_KEY|" "$PROJECT_DIR/.env"
rm -f "$PROJECT_DIR/.env.bak"
echo -e "${GREEN}Updated VITE_SUPABASE_URL and VITE_SUPABASE_KEY in .env${NC}"

# ── Sync DB passwords if regenerating with existing volume ──
if [[ "$REGENERATING" == "true" ]] && command -v docker &>/dev/null; then
  DB_CONTAINER="the_family-supabase-db-1"
  if docker ps --format '{{.Names}}' 2>/dev/null | grep -q "$DB_CONTAINER"; then
    echo ""
    echo -e "${CYAN}Syncing new password to existing database roles...${NC}"
    docker exec "$DB_CONTAINER" psql -h localhost -U supabase_admin -d postgres -c "
      ALTER ROLE supabase_auth_admin WITH PASSWORD '$POSTGRES_PASSWORD';
      ALTER ROLE authenticator WITH PASSWORD '$POSTGRES_PASSWORD';
      ALTER ROLE postgres WITH PASSWORD '$POSTGRES_PASSWORD';
      ALTER ROLE supabase_storage_admin WITH PASSWORD '$POSTGRES_PASSWORD';
    " >/dev/null 2>&1
    if [ $? -eq 0 ]; then
      echo -e "${GREEN}Database role passwords updated${NC}"
    else
      echo -e "${YELLOW}Could not update DB passwords. If auth/rest fail to start, run:${NC}"
      echo "   docker compose down && docker volume rm the_family_supabase-db-data && cyfr up"
    fi
  elif docker volume ls --format '{{.Name}}' 2>/dev/null | grep -q "the_family_supabase-db-data"; then
    echo ""
    echo -e "${YELLOW}Existing DB volume detected with old passwords.${NC}"
    echo -e "${YELLOW}Delete it to start fresh, or start the DB first and re-run this script:${NC}"
    echo "   docker volume rm the_family_supabase-db-data"
  fi
fi

# ── Print next steps ──
echo ""
echo -e "${BOLD}═══════════════════════════════════════════════${NC}"
echo -e "${BOLD} Setup complete!${NC}"
echo -e "${BOLD}═══════════════════════════════════════════════${NC}"
echo ""
echo -e "${CYAN}1. Start everything:${NC}"
echo "   cyfr up"
echo ""
echo -e "${CYAN}2. Set CYFR secrets (so the Supabase catalyst can reach the local instance):${NC}"
echo "   cyfr secret set SUPABASE_URL=http://supabase-kong:8000"
echo "   cyfr secret set SUPABASE_PUBLISHABLE_KEY=$ANON_KEY"
echo "   cyfr secret set SUPABASE_SECRET_KEY=$SERVICE_ROLE_KEY"
echo ""
echo -e "${CYAN}3. Grant secrets to the Supabase catalyst:${NC}"
echo "   cyfr secret grant c:moonmoon69.supabase SUPABASE_URL"
echo "   cyfr secret grant c:moonmoon69.supabase SUPABASE_PUBLISHABLE_KEY"
echo "   cyfr secret grant c:moonmoon69.supabase SUPABASE_SECRET_KEY"
echo ""
echo -e "${CYAN}4. Set host policy for the Supabase catalyst:${NC}"
echo "   cyfr policy set c:moonmoon69.supabase:0.2.0 allowed_domains '[\"supabase-kong\"]'"
echo "   cyfr policy set c:moonmoon69.supabase:0.2.0 allowed_private_ips '[\"172.16.0.0/12\"]'"
echo ""
echo -e "${BOLD}Supabase Studio:${NC}"
echo "   URL:      http://localhost:8000"
echo "   Username: admin"
echo "   Password: $DASHBOARD_PASSWORD"
echo ""
echo -e "${GREEN}Schema auto-applies on first boot — no manual SQL needed.${NC}"
